# Generated by Django 4.0.2 on 2022-06-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('employee_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Technical Helpdesk', 'Technical Helpdesk'), ('Helpdest', 'Helpdesk'), ('Management Information System', 'Management Information System')], default='Not Selected', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_name', models.CharField(max_length=150, null=True)),
                ('asset_serial_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('Alloted', 'Alloted'), ('Unalloted', 'Unalloted')], max_length=50, null=True)),
                ('asset_category', models.CharField(choices=[('Electronic', 'Electronic'), ('Stationary', 'Stationary'), ('Furniture', 'Furniture'), ('Appliances', 'Appliances')], max_length=50, null=True)),
                ('asset_host_id', models.CharField(max_length=100, null=True, unique=True)),
                ('vendor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoice/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Alloted', 'Alloted'), ('Unalloted', 'Unalloted')], default='Unalloted', max_length=15, null=True)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetApp.employee')),
            ],
            options={
                'ordering': ['asset_name'],
            },
        ),
    ]
