# Generated by Django 4.0.2 on 2022-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_host_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
