# Generated by Django 4.0.2 on 2022-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0002_remove_asset_asset_type_alter_asset_asset_host_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='status',
            new_name='asset_status',
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
